version: '3.5'
services:

  transactions-api:
    container_name: transactions-api
    image: transactions_api:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATASOURCE_URL: ${DATASOURCE_URL}
    ports:
      - "8082:8082"
    networks:
      - pismo-network
    restart: unless-stopped

networks:
  pismo-network:
    external: true